# -*- coding: utf-8 -*-
"""ccnew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L08Vdu-fZkMfeMIHhhfKHwe6mcmGDdMU
"""

!pip install -q gdown h5py

import h5py, numpy as np, cv2, os, glob, random, torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
import torchvision.transforms as T
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
from torch.cuda.amp import autocast, GradScaler
import PIL.Image as Image

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {device}")

# import os, glob


# print("=== Current directory ===")
# print(os.listdir('.'))

# print("\n=== Search for any jpg or h5 files ===")
# jpgs = glob.glob('./**/*.jpg', recursive=True)
# h5s  = glob.glob('./**/*.h5',  recursive=True)
# print(f"jpg files found: {len(jpgs)}")
# print(f"h5  files found: {len(h5s)}")
# if jpgs: print("sample jpg:", jpgs[0])
# if h5s:  print("sample h5: ", h5s[0])

from google.colab import files

print("Upload your kaggle.json")
print("Get it from: kaggle.com → Settings → API → Create New Token")
uploaded = files.upload()

os.makedirs('/root/.kaggle', exist_ok=True)
with open('/root/.kaggle/kaggle.json', 'wb') as f:
    f.write(uploaded['kaggle.json'])
os.chmod('/root/.kaggle/kaggle.json', 0o600)

!pip install -q kaggle
!kaggle datasets list -s shanghaitech

!kaggle datasets download -d tthien/shanghaitech-with-people-density-map --force
!ls *.zip

import zipfile, glob, shutil, os

with zipfile.ZipFile('shanghaitech-with-people-density-map.zip', 'r') as z:
    z.extractall('raw')
found = glob.glob('raw/**/part_A', recursive=True)

if found:
    parent = os.path.dirname(found[0])
    print(f"Moving {parent} → ShanghaiTech")
    if os.path.exists('ShanghaiTech'):
        shutil.rmtree('ShanghaiTech')
    shutil.move(parent, 'ShanghaiTech')
else:
    # If part_A not found directly, search one level deeper
    found2 = glob.glob('raw/**/**/part_A', recursive=True)
    print("Deeper search:", found2)
    if found2:
        parent = os.path.dirname(found2[0])
        if os.path.exists('ShanghaiTech'):
            shutil.rmtree('ShanghaiTech')
        shutil.move(parent, 'ShanghaiTech')

# Final verify
for part in ['A', 'B']:
    for split in ['train', 'test']:
        imgs = glob.glob(f"ShanghaiTech/part_{part}/{split}_data/images/*.jpg")
        h5s  = glob.glob(f"ShanghaiTech/part_{part}/{split}_data/ground-truth-h5/*.h5")
        print(f"Part {part} {split}: {len(imgs)} images | {len(h5s)} h5 files")

# img_path = './ShanghaiTech/part_A/train_data/images/IMG_1.jpg'
# gt_path  = './ShanghaiTech/part_A/train_data/ground-truth-h5/IMG_1.h5'

# img = Image.open(img_path).convert('RGB')
# gt  = h5py.File(gt_path, 'r')
# dm  = np.asarray(gt['density'])

# print(f"Image shape:     {np.array(img).shape}")
# print(f"Density shape:   {dm.shape}")
# print(f"Density sum:     {dm.sum():.1f}")
# print(f"Keys in h5 file: {list(gt.keys())}")

# “This dataset class loads images and their corresponding density maps,
# applies resizing and normalization, performs data augmentation during training,
# and downsamples density maps to match the model output resolution while preserving total count.
# The DataLoader then batches and efficiently feeds this data to the model.”

import random
import numpy as np
import torch

def set_seed(seed=42):
    random.seed(seed)                # Python random
    np.random.seed(seed)             # NumPy
    torch.manual_seed(seed)          # PyTorch (CPU)
    torch.cuda.manual_seed(seed)     # PyTorch (GPU)
    torch.cuda.manual_seed_all(seed) # Multi-GPU

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    torch.use_deterministic_algorithms(True, warn_only=True)

    print(f"Seed set to {seed}")

class ShanghaiTechDataset(Dataset):
    MEAN   = [0.485, 0.456, 0.406]
    STD    = [0.229, 0.224, 0.225]
    CROP   = 512
    STRIDE = 8

    def __init__(self, part='A', split='train'):
        self.split   = split
        self.h5_dir  = f"./ShanghaiTech/part_{part}/{split}_data/ground-truth-h5"
        img_dir      = f"./ShanghaiTech/part_{part}/{split}_data/images"

        all_imgs = sorted(glob.glob(os.path.join(img_dir, "*.jpg")))
        self.img_paths = [
            p for p in all_imgs
            if os.path.exists(os.path.join(self.h5_dir, Path(p).stem + ".h5"))
        ]
        assert len(self.img_paths) > 0, \
            f"No pairs found. img_dir={img_dir}  h5_dir={self.h5_dir}"
        print(f"Part {part} {split}: {len(self.img_paths)} pairs")
        self.tf = T.Compose([
            T.ToTensor(),
            T.Normalize(self.MEAN, self.STD)
        ])

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        stem    = Path(self.img_paths[idx]).stem
        img     = cv2.cvtColor(cv2.imread(self.img_paths[idx]), cv2.COLOR_BGR2RGB)
        with h5py.File(os.path.join(self.h5_dir, stem + ".h5"), 'r') as f:
            density = np.asarray(f['density'], dtype=np.float32)

        h, w    = img.shape[:2]
        scale   = self.CROP / min(h, w)
        nh, nw  = max(self.CROP, int(h*scale)), max(self.CROP, int(w*scale))
        img     = cv2.resize(img,     (nw, nh), interpolation=cv2.INTER_LINEAR)
        density = cv2.resize(density, (nw, nh), interpolation=cv2.INTER_LINEAR)
        density *= (h * w) / (nh * nw)

        if self.split == 'train':
            top  = random.randint(0, nh - self.CROP)
            left = random.randint(0, nw - self.CROP)
            if random.random() > 0.5:
                img     = np.fliplr(img).copy()
                density = np.fliplr(density).copy()
        else:
            top  = (nh - self.CROP) // 2
            left = (nw - self.CROP) // 2

        img     = img[top:top+self.CROP, left:left+self.CROP]
        density = density[top:top+self.CROP, left:left+self.CROP]

        out     = self.CROP // self.STRIDE
        den_out = cv2.resize(density, (out, out),
                             interpolation=cv2.INTER_LINEAR) * self.STRIDE**2

        return self.tf(img), torch.from_numpy(den_out).unsqueeze(0).float()

set_seed(42)
PART         = 'A'
train_ds     = ShanghaiTechDataset(PART, 'train')
test_ds      = ShanghaiTechDataset(PART, 'test')
train_loader = DataLoader(train_ds, batch_size=4, shuffle=True,
                          num_workers=2, pin_memory=True, drop_last=True)
test_loader  = DataLoader(test_ds,  batch_size=1, shuffle=False,
                          num_workers=2, pin_memory=True)

img, den = train_ds[0]
print(f"Image:   {img.shape}")
print(f"Density: {den.shape}")
print(f"Count:   {den.sum():.1f}")

class ChannelAttention(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        mid      = max(channels // reduction, 8)
        self.avg = nn.AdaptiveAvgPool2d(1)
        self.max = nn.AdaptiveMaxPool2d(1)
        self.fc  = nn.Sequential(
            nn.Conv2d(channels, mid, 1, bias=False),
            nn.ReLU(inplace=True),
            nn.Conv2d(mid, channels, 1, bias=False),
        )
        self.sig = nn.Sigmoid()
    def forward(self, x):
        return self.sig(self.fc(self.avg(x)) + self.fc(self.max(x)))

class SpatialAttention(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, 7, padding=3, bias=False)
        self.sig  = nn.Sigmoid()
    def forward(self, x):
        avg = x.mean(dim=1, keepdim=True)
        mx  = x.max(dim=1,  keepdim=True).values
        return self.sig(self.conv(torch.cat([avg, mx], dim=1)))

class CBAM(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.ca = ChannelAttention(channels)
        self.sa = SpatialAttention()
    def forward(self, x):
        return x * self.ca(x) * self.sa(x)

def dilated_block(in_ch, out_ch, d=2):
    return nn.Sequential(
        nn.Conv2d(in_ch, out_ch, 3, padding=d, dilation=d, bias=False),
        nn.BatchNorm2d(out_ch),
        nn.ReLU(inplace=True),
    )

class CrowdCountingNet(nn.Module):
    def __init__(self, pretrained=True):
        super().__init__()
        vgg            = models.vgg16_bn(weights='DEFAULT' if pretrained else None)
        self.frontend  = nn.Sequential(*list(vgg.features.children())[:33])
        self.backend   = nn.Sequential(
            dilated_block(512, 512, 1),
            dilated_block(512, 512, 2),
            dilated_block(512, 512, 2),
            dilated_block(512, 256, 2),
            dilated_block(256, 128, 2),
            dilated_block(128,  64, 2),
        )
        self.attention   = CBAM(64)
        self.output_conv = nn.Sequential(
            nn.Conv2d(64, 1, 1),
            nn.ReLU(inplace=True),
        )
        self._init_weights()

    def _init_weights(self):
        for m in list(self.backend.modules()) + list(self.output_conv.modules()):
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, x):
        x = self.frontend(x)
        x = self.backend(x)
        x = self.attention(x)
        return self.output_conv(x)


model = CrowdCountingNet(pretrained=True).to(device)
dummy = torch.randn(1, 3, 512, 512).to(device)
with torch.no_grad():
    out = model(dummy)
print(f"Input:  {dummy.shape}")
print(f"Output: {out.shape}")

EPOCHS   = 100
os.makedirs('checkpoints', exist_ok=True)

optimizer = torch.optim.Adam([
    {'params': model.frontend.parameters(),    'lr': 1e-5},
    {'params': model.backend.parameters(),     'lr': 1e-4},
    {'params': model.attention.parameters(),   'lr': 1e-4},
    {'params': model.output_conv.parameters(), 'lr': 1e-4},
], weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=EPOCHS, eta_min=1e-7
)
criterion = nn.MSELoss()
scaler    = GradScaler()
best_mae  = float('inf')

print(f"{'Epoch':>5} | {'Loss':>10} | {'MAE':>8} | {'RMSE':>8} | {'Best':>8}")
print("-" * 50)

for epoch in range(1, EPOCHS + 1):

    model.train()
    total_loss = 0
    for imgs, dens in train_loader:
        imgs, dens = imgs.to(device), dens.to(device)
        optimizer.zero_grad()
        with autocast():
            pred = model(imgs)
            loss = criterion(pred, dens)
        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        scaler.step(optimizer)
        scaler.update()
        total_loss += loss.item()
    scheduler.step()

    if epoch % 5 == 0 or epoch == 1:
        model.eval()
        mae, mse, n = 0.0, 0.0, 0
        with torch.no_grad():
            for imgs, dens in test_loader:
                imgs, dens = imgs.to(device), dens.to(device)
                with autocast():
                    pred = model(imgs)
                diff  = abs(pred.sum().item() - dens.sum().item())
                mae  += diff
                mse  += diff ** 2
                n    += 1
        mae  = mae / n
        rmse = (mse / n) ** 0.5
        if mae < best_mae:
            best_mae = mae
            torch.save(model.state_dict(), 'checkpoints/best_model.pth')
        print(f"{epoch:>5} | {total_loss/len(train_loader):>10.4f} "
              f"| {mae:>8.2f} | {rmse:>8.2f} | {best_mae:>8.2f}")
    else:
        print(f"  epoch {epoch}/{EPOCHS}  loss={total_loss/len(train_loader):.4f}", end='\r')

print(f"\nDone. Best MAE = {best_mae:.2f}")

torch.save(model.state_dict(), "best_model.pth")

import matplotlib.pyplot as plt

model.load_state_dict(torch.load('checkpoints/best_model.pth', map_location=device))
model.eval()

test_imgs = sorted(glob.glob(
    f"ShanghaiTech/part_{PART}/test_data/images/*.jpg"
))[:4]
h5_dir = f"ShanghaiTech/part_{PART}/test_data/ground-truth-h5"

fig, axes = plt.subplots(len(test_imgs), 3, figsize=(14, 4*len(test_imgs)))

MEAN = torch.tensor([0.485, 0.456, 0.406]).view(3,1,1)
STD  = torch.tensor([0.229, 0.224, 0.225]).view(3,1,1)

for i, img_path in enumerate(test_imgs):
    stem = Path(img_path).stem
    img  = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
    h, w = img.shape[:2]

    with h5py.File(os.path.join(h5_dir, stem + ".h5"), 'r') as f:
        gt_count = np.asarray(f['density']).sum()

    # pad to stride multiple
    ph = (8 - h % 8) % 8
    pw = (8 - w % 8) % 8
    img_pad = np.pad(img, ((0,ph),(0,pw),(0,0)), mode='reflect')

    tensor = (torch.from_numpy(img_pad).float().permute(2,0,1)/255.0 - MEAN) / STD
    tensor = tensor.unsqueeze(0).to(device)

    with torch.no_grad(), autocast():
        pred = model(tensor)

    pred_np  = pred.squeeze().cpu().float().numpy()
    pred_up  = cv2.resize(pred_np, (w, h), interpolation=cv2.INTER_LINEAR)
    pred_count = float(pred.sum().cpu())

    axes[i][0].imshow(img);           axes[i][0].set_title("Input");             axes[i][0].axis('off')
    axes[i][1].imshow(pred_up, cmap='jet'); axes[i][1].set_title("Density map"); axes[i][1].axis('off')
    axes[i][2].imshow(img)
    axes[i][2].imshow(pred_up, cmap='jet', alpha=0.5)
    axes[i][2].set_title(f"GT={gt_count:.0f}  Pred={pred_count:.1f}  Err={abs(pred_count-gt_count):.1f}")
    axes[i][2].axis('off')

plt.suptitle(f"Part {PART} — Test predictions", y=1.01)
plt.tight_layout()
plt.show()